### ISSUE TITLE
Week 7 Qwiklabs Assessment: Log Analysis Using Regular Expressions

### ISSUE THREAD

**Issue by winshikhar** [jeremymaya/google-it-automation-with-python#83]
Would you be able to share the final assessment code with us?

**Comment by jeremymaya** [comment]
No, I cant. As to help you though, I recommend copying the syslog.log to your local machine and try to come up with the answer. I used re, operator and csv modules to complete the assessment.

Also below link will help you with the assessment as well:
[Writing a dictionary to a csv file with one line for every 'key: value'](https://stackoverflow.com/questions/8685809/writing-a-dictionary-to-a-csv-file-with-one-line-for-every-key-value)
