### ISSUE TITLE
I cant solve week 2

### ISSUE THREAD

**Issue by kub3r** [jeremymaya/google-it-automation-with-python#93]
Can you please help me complete the course.

**Comment by jeremymaya** [comment]
Hello Kuber, 

How can I help you with Week 2? I cannot share the code directly but I can try to help you guide to the right direction!

**Comment by kub3r** [comment]
I tried importing csv but it shows error all the time.
If you just solve it for me it would be great.

**Comment by jeremymaya** [comment]
It may be self-explanatory once you go through some of the debugging questions:

* What error messages are you getting?
* Are you importing the csv module with ```import csv``` ?
* Do you have the csv file you are trying to open?
* Is your csv file path set correctly?
* If you were able to open the csv file, can you print the content of the file?
