### ISSUE TITLE
Can not solve week 2 final assignment

### ISSUE THREAD

**Issue by groverHarshit** [jeremymaya/google-it-automation-with-python#94]
Hi
I was solving week2 assignment last night.
In which I got two files, dailysync.py and multisync.py
I read the instructions and as far as I am clear, we need to edit dailysync.py
But I don't know what to edit. We have `src = '/data/prod' ` and `dst = '/data/prod_back`
Could you please assist what to do next?

**Comment by jeremymaya** [comment]
Hey there, I don't recall working on dailysync.py and multisync.py during the course (it's been a while). However, it seems like we are opening a file from the ```src``` and saving an output to the ```dst``` directory.

The first thing I would do is open the file from the ```src``` and print the content to get a better understanding of what you need to work on. After that, modify the python script to work on the assignment.

**Comment by groverHarshit** [comment]
`User exercise
Now that you understand how multiprocessing works, let's fix CPU bound so that it doesn't take more than 20 hours to finish. Try applying multiprocessing, which takes advantage of the idle CPU cores for parallel processing.

Open the dailysync.py Python script in the nano editor that needs to be modified. It's similar to multisync.py that utilizes idle CPU cores for the backup.

nano ~/scripts/dailysync.py

Here, you have to use multiprocessing and subprocess module methods to sync the data from /data/prod to /data/prod_backup folder.

Hint: os.walk() generates the file names in a directory tree by walking the tree either top-down or bottom-up. This is used to traverse the file system in Python.
Once you're done writing the Python script, save the file by clicking Ctrl-o, the Enter key, and Ctrl-x.`



`This is my exercise. If you could remember that would be a lot.`

**Comment by groverHarshit** [comment]
Never mind. I solved that already. Thanks
