### ISSUE TITLE
Uing-python-to-interact-with-operating system

### ISSUE THREAD

**Issue by BhartiAbhinav** [jeremymaya/google-it-automation-with-python#97]
Please help with using python to interact with operating systems week 7 assignment named as final.sh in your repository.

**Comment by BhartiAbhinav** [comment]
I really need help with that please help me out.

**Comment by ghost** [comment]
isn't that like your final...

**Comment by BhartiAbhinav** [comment]
Yes. I am having problems. Could you help me please?

**Comment by BhartiAbhinav** [comment]
Done! Solved it myself.
